name: Label New Issues

on:
  issues:
    types:
      - opened

permissions: 
  issues: write

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.2
        with:
          add-labels: "NEW ISSUE"
          ignore-if-labeled: true
