name: Label New Issues

on:
  issues:
    types:
      - opened

permissions: 
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest
      - name: Add inital label
        uses: andymckay/labeler@master
        with:
          add-labels: "NEW ISSUE"
          ignore-if-labeled: true
