name: Label New Issues

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      # 1. Füge das Label hinzu, wenn ein neues Issue erstellt wird
      - name: Add Label to New Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const labelToAdd = "NEW ISSUE";

            // Prüfen, ob das Issue bereits Labels hat
            if (issue.labels.length === 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [labelToAdd],
              });
            } else {
              console.log("Issue already has labels, no action taken.");
            }
